// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractException, util;

  util = require('util');

  AbstractException = function(message, constr) {
    if (message == null) {
      message = 'Error';
    }
    if (constr == null) {
      constr = this;
    }
    Error.captureStackTrace(this, constr);
    return this.message = message;
  };

  util.inherits(AbstractException, Error);

  AbstractException.prototype.name = 'Abstract Exception';

  module.exports = AbstractException;

}).call(this);
