// Generated by CoffeeScript 1.6.3
(function() {
  var CompileException, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CompileException = (function(_super) {
    __extends(CompileException, _super);

    function CompileException() {
      _ref = CompileException.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return CompileException;

  })(Error);

  module.exports = CompileException;

}).call(this);
