// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractException, CompileException, util;

  util = require('util');

  AbstractException = require('./AbstractException');

  CompileException = function(message) {
    return CompileException.super_.call(this, message, this.constructor);
  };

  util.inherits(CompileException, AbstractException);

  CompileException.prototype.name = 'Compile Exception';

  module.exports = CompileException;

}).call(this);
