// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractException, HttpGetException, util;

  util = require('util');

  AbstractException = require('./AbstractException');

  HttpGetException = function(message) {
    return HttpGetException.super_.call(this, message, this.constructor);
  };

  util.inherits(HttpGetException, AbstractException);

  HttpGetException.prototype.name = 'Http Get Exception';

  module.exports = HttpGetException;

}).call(this);
