// Generated by CoffeeScript 1.6.3
(function() {
  var InvalidArgumentException, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InvalidArgumentException = (function(_super) {
    __extends(InvalidArgumentException, _super);

    function InvalidArgumentException() {
      _ref = InvalidArgumentException.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return InvalidArgumentException;

  })(Error);

  module.exports = InvalidArgumentException;

}).call(this);
