// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractException, InvalidArgumentException, util;

  util = require('util');

  AbstractException = require('./AbstractException');

  InvalidArgumentException = function(message) {
    return InvalidArgumentException.super_.call(this, message, this.constructor);
  };

  util.inherits(InvalidArgumentException, AbstractException);

  InvalidArgumentException.prototype.name = 'Invalid Argument Exception';

  module.exports = InvalidArgumentException;

}).call(this);
