// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, cleanCss, htmlMinifier, uglify;

  uglify = require('uglify-js');

  cleanCss = require('clean-css');

  htmlMinifier = require('html-minifier');

  Helpers = (function() {
    function Helpers() {}

    Helpers.minify = {
      js: function(data) {
        return uglify.minify(data, {
          fromString: true
        }).code;
      },
      css: function(data) {
        return cleanCss().minify(data);
      },
      html: function(data) {
        data = htmlMinifier.minify(data, {
          removeComments: true,
          removeCommentsFromCDATA: true,
          removeCDATASectionsFromCDATA: true,
          collapseWhitespace: true,
          collapseBooleanAttributes: true,
          removeRedundantAttributes: true,
          removeEmptyAttributes: true
        });
        return data;
      }
    };

    Helpers.jquerify = {
      precompiled: function(data) {
        return "function (values, data) {\nvar $ = jQuery, result = $();\nvalues = $.makeArray(values);\ndata = data || {};\nfor (var i=0; i < values.length; i++) {\nvar value = $.extend({}, values[i], data, {index: i});\nvar elem  = $((" + data + ")(value));\nelem.data('item', value);\n$.merge(result, elem);\n}\nreturn result;\n};";
      },
      compiled: function(data) {
        data = data.replace(/\'/g, "\\'");
        data = data.replace(/\n/g, "' +\n'");
        data = data.replace(/[\s\+]+$/, '');
        return "(function() {\n$('" + data + "');\n}).call(this);";
      }
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
