// Generated by CoffeeScript 1.6.3
(function() {
  var Compiler;

  Compiler = (function() {
    function Compiler() {}

    Compiler.prototype.isCachableWithDependencies = function() {
      return false;
    };

    Compiler.prototype.getMinifier = function() {
      throw new Error('Method getMinifier is not implemented.');
    };

    Compiler.prototype.parse = function(data, options) {
      if (options == null) {
        options = {};
      }
      throw new Error('Method parse is not implemented.');
    };

    Compiler.prototype.parseError = function(error, path) {
      throw new Error('Method parseError is not implemented.');
    };

    return Compiler;

  })();

  module.exports = Compiler;

}).call(this);
