// Generated by CoffeeScript 1.6.3
(function() {
  var Compiler, Eco, InvalidArgumentException, Q, eco, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Q = require('q');

  eco = require('eco');

  Compiler = require('./Compiler');

  InvalidArgumentException = require('../Exceptions/InvalidArgumentException');

  Eco = (function(_super) {
    __extends(Eco, _super);

    function Eco() {
      _ref = Eco.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Eco.prototype.getMinifier = function() {
      return 'uglify';
    };

    Eco.prototype.parse = function(data, options) {
      if (options == null) {
        options = {};
      }
      if (options.minify === true && options.jquerify === true) {

      } else if (options.minify === true) {
        return Q.reject(new InvalidArgumentException('Minifing eco templates is not implemented'));
      }
      if (options.precompile === true) {
        data = eco.precompile(data);
        if (options.jquerify === true) {
          data = Compiler.jquerify.precompiled(data);
        }
      } else {
        data = eco.render(data, options.data);
        if (options.jquerify === true) {
          data = Compiler.jquerify.compiled(data);
        }
      }
      return Q.resolve(data);
    };

    return Eco;

  })(Compiler);

  module.exports = Eco;

}).call(this);
